// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3SgJazvWm4A8qSB2kbZNXY-2_hDjKXcQ',
    appId: '1:742729565398:android:afdfc132582f7c5882b577',
    messagingSenderId: '742729565398',
    projectId: 'insta-clone-monday',
    storageBucket: 'insta-clone-monday.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsu4BdJEjOecm7Ksy0hpsp9GTlypz48MI',
    appId: '1:742729565398:ios:b97f6b3008b7a77782b577',
    messagingSenderId: '742729565398',
    projectId: 'insta-clone-monday',
    storageBucket: 'insta-clone-monday.appspot.com',
    androidClientId: '742729565398-2ijjsf6io5o69r3b71rh4tah5k9ddbof.apps.googleusercontent.com',
    iosClientId: '742729565398-s232d6g1oi2crcqr9jmkmi1r502da1vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
